# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.1.0

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    io.kubernetes.cri-o.TTY/todo-app-apiapi1: "false"
    io.kubernetes.cri-o.TTY/todo-app-apidb1: "false"
    io.podman.annotations.autoremove/todo-app-apiapi1: "FALSE"
    io.podman.annotations.autoremove/todo-app-apidb1: "FALSE"
    io.podman.annotations.init/todo-app-apiapi1: "FALSE"
    io.podman.annotations.init/todo-app-apidb1: "FALSE"
    io.podman.annotations.privileged/todo-app-apiapi1: "FALSE"
    io.podman.annotations.privileged/todo-app-apidb1: "FALSE"
    io.podman.annotations.publish-all/todo-app-apiapi1: "FALSE"
    io.podman.annotations.publish-all/todo-app-apidb1: "FALSE"
    org.opencontainers.image.base.digest/todo-app-apiapi1: sha256:a06eaf1b747ba5db1a15aba7a2ced8f7159d22eb210a79820f19a038
    org.opencontainers.image.base.name/todo-app-apiapi1: docker.io/library/rust:1.60
  creationTimestamp: "2022-07-26T08:39:55Z"
  labels:
    app: todo-app-apidb1-pod
  name: todo-app-apidb1-pod
spec:
  ports:
  - name: "5432"
    nodePort: 30056
    port: 5432
    targetPort: 5432
  - name: "8080"
    nodePort: 31277
    port: 8080
    targetPort: 8080
  selector:
    app: todo-app-apidb1-pod
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.TTY/todo-app-apiapi1: "false"
    io.kubernetes.cri-o.TTY/todo-app-apidb1: "false"
    io.podman.annotations.autoremove/todo-app-apiapi1: "FALSE"
    io.podman.annotations.autoremove/todo-app-apidb1: "FALSE"
    io.podman.annotations.init/todo-app-apiapi1: "FALSE"
    io.podman.annotations.init/todo-app-apidb1: "FALSE"
    io.podman.annotations.privileged/todo-app-apiapi1: "FALSE"
    io.podman.annotations.privileged/todo-app-apidb1: "FALSE"
    io.podman.annotations.publish-all/todo-app-apiapi1: "FALSE"
    io.podman.annotations.publish-all/todo-app-apidb1: "FALSE"
    org.opencontainers.image.base.digest/todo-app-apiapi1: sha256:a06eaf1b747ba5db1a15aba7a2ced8f7159d22eb210a79820f19a038
    org.opencontainers.image.base.name/todo-app-apiapi1: docker.io/library/rust:1.60
  creationTimestamp: "2022-07-26T08:39:55Z"
  labels:
    app: todo-app-apidb1-pod
  name: todo-app-apidb1-pod
spec:
  containers:
  - args:
    - postgres
    env:
    - name: POSTGRES_DB
      value: app
    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata
    - name: POSTGRES_PASSWORD
      value: admin
    - name: POSTGRES_USER
      value: admin
    image: docker.io/library/postgres:9
    name: todo-app-apidb1
    ports:
    - containerPort: 5432
      hostPort: 5432
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: 3210f73288bc33eaf430268b2c53b82e5a7f958341831b578181ebb0c74ea6c9-pvc
    - mountPath: /var/lib/postgresql/data/pgdata
      name: todo-app-api_pgdata-pvc
  - command:
    - /bin/sh
    - -c
    - ./wait-for-it.sh db:5432 -- diesel migration run && cargo watch -x run
    image: localhost/todo-app-api_api:latest
    name: todo-app-apiapi1
    ports:
    - containerPort: 8080
      hostPort: 8080
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /app
      name: todo-app-api-api-host-0
    - mountPath: /usr/local/cargo
      name: 14eb6169b5872c29f389b4ba346077432ffb6e99c1dc38a65bf4d095b8c4630c-pvc
    - mountPath: /usr/local/cargo/registry
      name: todo-app-api_cargo-cache-pvc
    - mountPath: /app/target
      name: todo-app-api_target-cache-pvc
  volumes:
  - name: 3210f73288bc33eaf430268b2c53b82e5a7f958341831b578181ebb0c74ea6c9-pvc
    persistentVolumeClaim:
      claimName: 3210f73288bc33eaf430268b2c53b82e5a7f958341831b578181ebb0c74ea6c9
  - name: todo-app-api_pgdata-pvc
    persistentVolumeClaim:
      claimName: todo-app-api_pgdata
  - hostPath:
      path: /Users/seito.a.hirai/Documents/tdd/other/todo-app-api/api
      type: Directory
    name: todo-app-api-api-host-0
  - name: 14eb6169b5872c29f389b4ba346077432ffb6e99c1dc38a65bf4d095b8c4630c-pvc
    persistentVolumeClaim:
      claimName: 14eb6169b5872c29f389b4ba346077432ffb6e99c1dc38a65bf4d095b8c4630c
  - name: todo-app-api_cargo-cache-pvc
    persistentVolumeClaim:
      claimName: todo-app-api_cargo-cache
  - name: todo-app-api_target-cache-pvc
    persistentVolumeClaim:
      claimName: todo-app-api_target-cache
