version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/rust.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - todo-app-apidb1-pod
    volumes:
      - ./api:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    command: /bin/sh -c "./wait-for-it.sh todo-app-apidb1-pod:5432 -- diesel migration run && cargo watch -x run"

  todo-app-apidb1-pod:
    image: "postgres:9"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  cargo-cache:
  target-cache:
  pgdata: {}
